### ISSUE TITLE
CMake configuration out of directory may be incorrect

### ISSUE THREAD

**Issue by steven-varga** [vrtql/websockets#1]
Hi, I love your work! However when I try to configure + compile outside the directory tree I am getting `fatal error: common.h: No such file or directory` compile error. Changing `CMAKE_CURRENT_BINARY_DIR` to `CMAKE_CURRENT_SOURCE_DIR`  seem to fix it: 
```
CMakeLists.txt
[...]
#27 configure_file( ${CMAKE_CURRENT_SOURCE_DIR}/src/common.h.in
                ${CMAKE_CURRENT_SOURCE_DIR}/src/common.h )
```

**Comment by vrtql** [comment]
Thank you. I will fix asap.

**Comment by vrtql** [comment]
Fixed.
